### PR TITLE
variable

### PR DESCRIPTION
**Pull request by favour-121**

### CODE REVIEW

**Review by favour-22 — CHANGES_REQUESTED** [review]
did not add var

**Comment by favour-22** [comment]
merge

**Comment by favour-22** [comment]
add all

**Review by favour-22 — APPROVED** [review]

**Comment by favour-22** [comment]
all good

**Comment by TalleA15** [comment]
A variables is a characteristics of unit being observed that may assume more one of a set of valume to which a numerical measure or a etc....

In a programming  a variable is a value that can change, depending on condition or on information passed to the program. Typically, a program consists of etc.....

**Comment by TalleA15** [comment]
A variable is a data that convert from one language to another language like logic, css, java, etc......

**Comment by TalleA15** [comment]
approved

**Comment by favour-22** [comment]
Variables are like a container for storing data,I don't agree with you

**Pull request merged**
